GET http://localhost:3333/reviews

###

POST http://localhost:3333/reviews
Content-Type: application/json

{
    "content": "Game of Thrones",
    "title": "The best television series in the world",
    "text": "It's a series that leaves you wanting to watch the next episode every time an episode ends",
    "author": "Gabriel Rapucci Gonzalez",
    "rating": 5
}

###

PUT http://localhost:3333/reviews/ea8c5344-44fc-4272-b787-a1ef2ceff602
Content-Type: application/json

{
    "content": "GoT",
    "title": "The best series in the world!",
    "text": "It's a series that leaves you wanting to watch the next episode every time an episode ends, it's really good!",
    "author": "Gabriel Rapucci Gonzalez",
    "rating": 5
}

###

DELETE http://localhost:3333/reviews/ea8c5344-44fc-4272-b787-a1ef2ceff602